site_name: FogLedger Indy

theme:
  name: material
  palette:  
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: auto)'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
  language: en

repo_name: larsid/fogledger-indy
repo_url: https://github.com/MatheusNascimentoti99/FogLedger-Indy/
edit_uri: ""

extra:
  version:
    provider: mike

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/matheusnascimentoti99
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matheus-nascimento-322a0b181/

copyright: |
  &copy; 2023 <a href="https://github.com/MatheusNascimentoti99/FogLedger-Indy/"  target="_blank" rel="noopener">LARSID</a>

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: 'index.md'
  - Getting started: 'quickstart.md'
  - Emulation:
    - Local Emulation: 'indy/examples/test-local-network.md'
    - Using Webserver: 'indy/examples/test-local-webserver-network.md'
    - Distributed Emulation: 'indy/examples/test-distributed-network.md'
  - Resources:
    - Webserver: 'indy/resources/webserver.md'